# -*- coding: utf-8 -*-
"""Dancel, TA3, CS0065, AN42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ai6jwhf6yyEIGIgn1C44C3MMD3OVCijn
"""

# =====================================================================
# Intelligent Tutoring System - Case-Based Reasoning (CBR) System
# Fixed & Cleaned Implementation for Google Colab
# =====================================================================

class IntelligentTutoringCBR:
    def __init__(self):
        # Step 3: Define Case Base with 5 rich historical student cases
        self.case_base = [
            {
                "case_id": 1,
                "problem": {
                    "topic": "Quadratic Equations",
                    "error_type": "Formula Misuse",
                    "difficulty": "Medium"
                },
                "solution": {
                    "feedback": "You applied the quadratic formula incorrectly by missing the negative sign on the b term.",
                    "supplementary_lesson": "Review standard form ax^2 + bx + c = 0 and proper coefficient identification.",
                    "practice_problem": "Solve: 2x^2 - 4x - 6 = 0"
                }
            },
            {
                "case_id": 2,
                "problem": {
                    "topic": "Fraction Operations",
                    "error_type": "Common Denominator Error",
                    "difficulty": "Easy"
                },
                "solution": {
                    "feedback": "You added denominators directly instead of finding a Least Common Denominator (LCD).",
                    "supplementary_lesson": "Lesson on finding LCD for heterogeneous fractions before addition or subtraction.",
                    "practice_problem": "Evaluate: 1/4 + 2/3"
                }
            },
            {
                "case_id": 3,
                "problem": {
                    "topic": "Derivative Rules",
                    "error_type": "Chain Rule Omission",
                    "difficulty": "Hard"
                },
                "solution": {
                    "feedback": "You forgot to multiply by the derivative of the inner function when applying the chain rule.",
                    "supplementary_lesson": "Step-by-step breakdown of composite functions and chain rule formula: d/dx[f(g(x))] = f'(g(x)) * g'(x).",
                    "practice_problem": "Find derivative of: f(x) = (3x^2 + 5)^4"
                }
            },
            {
                "case_id": 4,
                "problem": {
                    "topic": "Quadratic Equations",
                    "error_type": "Factoring Error",
                    "difficulty": "Easy"
                },
                "solution": {
                    "feedback": "Your factoring of the quadratic expression into binomials yielded incorrect roots.",
                    "supplementary_lesson": "Review grouping methods and finding factors of 'ac' that sum up to 'b'.",
                    "practice_problem": "Factor completely: x^2 + 5x + 6"
                }
            },
            {
                "case_id": 5,
                "problem": {
                    "topic": "Integration Techniques",
                    "error_type": "Substitution Error",
                    "difficulty": "Hard"
                },
                "solution": {
                    "feedback": "You incorrectly assigned the 'u' variable and omitted the differential factor du scaling.",
                    "supplementary_lesson": "Comprehensive review of u-substitution, choosing inner terms, and adjusting constants.",
                    "practice_problem": "Evaluate: Integral of 2x(x^2 + 3)^4 dx"
                }
            }
        ]

    def retrieve(self, new_problem):
        print("\n" + "="*70)
        print("[STEP 1] RETRIEVAL STAGE: Executing Weighted Similarity Assessment")
        print("="*70)
        print(f"-> Incoming Student Problem Description:")
        print(f"   • Topic      : {new_problem['topic']}")
        print(f"   • Error Type : {new_problem['error_type']}")
        print(f"   • Difficulty : {new_problem['difficulty']}")
        print("-" * 70)

        best_match = None
        highest_score = -1

        # Step 4: Implement detailed weighted similarity scoring mechanism
        # Topic carries 50% weight, Error Type carries 35% weight, Difficulty carries 15% weight
        for case in self.case_base:
            score = 0.0

            if case["problem"]["topic"].lower() == new_problem["topic"].lower():
                score += 0.50
            if case["problem"]["error_type"].lower() == new_problem["error_type"].lower():
                score += 0.35
            if case["problem"]["difficulty"].lower() == new_problem["difficulty"].lower():
                score += 0.15

            print(f"Evaluating Case #{case['case_id']} [{case['problem']['topic']} | {case['problem']['error_type']} | {case['problem']['difficulty']}]")
            print(f"   -> Computed Similarity Score: {score:.2f}")

            if score > highest_score:
                highest_score = score
                best_match = case

        print("-" * 70)
        print(f"✔ Retrieval Result: Most relevant past case identified is Case #{best_match['case_id']} with a match score of {highest_score:.2f}.")
        return best_match, highest_score

    def adapt(self, retrieved_case, new_problem):
        print("\n" + "="*70)
        print("[STEP 2] ADAPTATION STAGE: Customizing Solution Strategy")
        print("="*70)

        # Copy solution dictionary to prevent mutation of the historical case base
        adapted_solution = retrieved_case["solution"].copy()

        # Step 5: ITS adaptation logic (scaling complexity based on student difficulty delta)
        print(f"-> Base Case Difficulty : {retrieved_case['problem']['difficulty']}")
        print(f"-> New Student Difficulty: {new_problem['difficulty']}")

        if new_problem["difficulty"] != retrieved_case["problem"]["difficulty"]:
            print(f"-> Action: Adapting practice problem parameters for a '{new_problem['difficulty']}' proficiency level.")
            adapted_solution["practice_problem"] = (
                f"{adapted_solution['practice_problem']} "
                f"[Adjusted complexity tier: Scaled for {new_problem['difficulty']} academic standard]"
            )
        else:
            print("-> Action: Difficulty levels align. Retaining standard practice problem context.")

        adapted_solution["feedback"] = (
            f"Personalized Diagnostic Feedback: {adapted_solution['feedback']} "
            f"(Targeted specifically for current submission context under topic '{new_problem['topic']}'.)"
        )

        print("✔ Adaptation successfully completed.")
        return adapted_solution

    def retain(self, new_problem, final_solution):
        print("\n" + "="*70)
        print("[STEP 3] RETAIN (LEARNING) STAGE: Updating Knowledge Base")
        print("="*70)

        new_case_id = len(self.case_base) + 1
        new_case = {
            "case_id": new_case_id,
            "problem": new_problem,
            "solution": final_solution
        }

        # Append new learning experience to case base
        self.case_base.append(new_case)

        print(f"✔ Status: 'New case saved' successfully as Case #{new_case_id}.")
        print(f"-> Total active cases in system memory: {len(self.case_base)}")

        print("\n-> Updated Comprehensive Case Base Directory:")
        for case in self.case_base:
            print(f"   [Case #{case['case_id']}] Topic: {case['problem']['topic']:<22} | Error: {case['problem']['error_type']:<24} | Level: {case['problem']['difficulty']}")

# --- Execution Driver ---
if __name__ == "__main__":
    # Initialize the CBR system
    its_cbr = IntelligentTutoringCBR()

    # Define a new challenging student submission scenario
    new_student_submission = {
        "topic": "Quadratic Equations",
        "error_type": "Formula Misuse",
        "difficulty": "Hard"
    }

    # Execute full CBR workflow cycles
    retrieved_case, similarity_score = its_cbr.retrieve(new_student_submission)
    adapted_solution = its_cbr.adapt(retrieved_case, new_student_submission)

    print("\n" + "="*70)
    print("FINAL PROGRAM OUTPUT: GENERATED TUTORING RESPONSE")
    print("="*70)
    for key, value in adapted_solution.items():
        print(f"• {key.replace('_', ' ').capitalize()}: {value}")

    # Retain the newly processed case into the system
    its_cbr.retain(new_student_submission, adapted_solution)