# -*- coding: utf-8 -*-
"""Dancel, TA2, CS0065, AN42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewachy1pu2EHtudubzJWwT5eePZ4wWuX
"""

import random
import time

# ==========================================
# TASK 1: Environment Setup
# ==========================================

def is_room_dirty(environment, room_name):
    """Check if a given room is dirty."""
    return environment.get(room_name, "").lower() == "dirty"

def clean_room(environment, room_name):
    """Clean the specified room."""
    environment[room_name] = "Clean"

# ==========================================
# TASK 2: Rule-Based Vacuum Agent Implementation
# ==========================================

class VacuumAgent:
    def __init__(self, current_location="A"):
        self.current_location = current_location

    def move_2_rooms(self):
        """Move method for Task 2 (2-room environment)."""
        if self.current_location == "A":
            self.current_location = "B"
        else:
            self.current_location = "A"

    def move_3_rooms(self, environment):
        """
        Move method for Bonus Task (3-room environment).
        Prioritizes moving to a random dirty room; otherwise selects any other room.
        """
        other_rooms = [r for r in environment.keys() if r != self.current_location]
        dirty_rooms = [r for r in other_rooms if is_room_dirty(environment, r)]

        if dirty_rooms:
            self.current_location = random.choice(dirty_rooms)
        else:
            self.current_location = random.choice(other_rooms)

    def perceive_and_act(self, environment, is_three_rooms=False):
        """
        Perceive state and apply rules:
        Rule 1: If current room is dirty, clean it.
        Rule 2: If current room is clean, move to another room.
        """
        curr_room = self.current_location

        if is_room_dirty(environment, curr_room):
            clean_room(environment, curr_room)
            action = f"Cleaned room {curr_room}"
        else:
            if is_three_rooms:
                self.move_3_rooms(environment)
            else:
                self.move_2_rooms()
            action = f"Moved to room {self.current_location}"

        return action

# ==========================================
# BONUS TASK: Visualizer
# ==========================================

def render_grid(environment, agent_location):
    """Renders a text-based visual grid of the environment and agent position."""
    rooms = list(environment.keys())
    top_border = "+" + "----------+" * len(rooms)

    header_row = "|"
    status_row = "|"
    agent_row  = "|"

    for r in rooms:
        header_row += f"  Room {r:2s}  |"
        status_row += f"  {environment[r]:5s}   |"
        agent_marker = "[ AGENT ]" if r == agent_location else "         "
        agent_row  += f" {agent_marker} |"

    print(top_border)
    print(header_row)
    print(status_row)
    print(agent_row)
    print(top_border)

# ==========================================
# TASK 3 & BONUS TASK: Run Simulations
# ==========================================

def run_standard_simulation():
    print("="*50)
    print("      STANDARD SIMULATION (2 ROOMS: A & B)      ")
    print("="*50)

    # 1. Environment Setup
    state_a = input("Enter initial state for Room A (Dirty/Clean): ").strip().capitalize()
    state_b = input("Enter initial state for Room B (Dirty/Clean): ").strip().capitalize()

    environment = {
        "A": state_a if state_a in ["Dirty", "Clean"] else "Dirty",
        "B": state_b if state_b in ["Dirty", "Clean"] else "Dirty"
    }

    start_loc = input("Enter starting room for Agent (A/B): ").strip().upper()
    if start_loc not in ["A", "B"]:
        start_loc = "A"

    steps = int(input("Enter number of simulation steps: "))

    agent = VacuumAgent(current_location=start_loc)

    print("\nStarting 2-Room Simulation...")
    print(f"Initial State: {environment}\n")

    for step in range(1, steps + 1):
        action = agent.perceive_and_act(environment, is_three_rooms=False)
        print(f"Step {step}:")
        print(f"  Agent Location: Room {agent.current_location}")
        print(f"  Action Taken  : {action}")
        print(f"  Env State     : {environment}")
        print("-" * 40)

def run_bonus_simulation():
    print("\n" + "="*50)
    print("      BONUS SIMULATION (3 ROOMS: A, B & C)      ")
    print("="*50)

    state_a = input("Enter initial state for Room A (Dirty/Clean): ").strip().capitalize()
    state_b = input("Enter initial state for Room B (Dirty/Clean): ").strip().capitalize()
    state_c = input("Enter initial state for Room C (Dirty/Clean): ").strip().capitalize()

    environment = {
        "A": state_a if state_a in ["Dirty", "Clean"] else "Dirty",
        "B": state_b if state_b in ["Dirty", "Clean"] else "Dirty",
        "C": state_c if state_c in ["Dirty", "Clean"] else "Dirty"
    }

    start_loc = input("Enter starting room for Agent (A/B/C): ").strip().upper()
    if start_loc not in ["A", "B", "C"]:
        start_loc = "A"

    steps = int(input("Enter number of simulation steps: "))

    agent = VacuumAgent(current_location=start_loc)

    print("\nStarting 3-Room Visual Simulation...")
    render_grid(environment, agent.current_location)

    for step in range(1, steps + 1):
        time.sleep(0.5) # Brief pause for step display
        action = agent.perceive_and_act(environment, is_three_rooms=True)
        print(f"\nStep {step}: {action}")
        render_grid(environment, agent.current_location)

# ==========================================
# MAIN EXECUTION
# ==========================================

if __name__ == "__main__":
    run_standard_simulation()

    run_bonus = input("\nDo you want to run the Bonus Task (3 Rooms with Grid Visuals)? (y/n): ").strip().lower()
    if run_bonus == 'y':
        run_bonus_simulation()