# -*- coding: utf-8 -*-
"""Dancel, TA1, CS0065, AN42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_A1Njzglw6Ua_QFtYJpG8Ff9NLiF299j
"""

# 1. Install required dependency for Google Colab
!pip install -q agentpy

import agentpy as ap
import random
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML

# -------- Get user input from console --------
try:
    num_agents = int(input("Enter number of agents (e.g., 5): ") or 5)
    grid_size = int(input("Enter grid size (e.g., 10 for 10x10): ") or 10)
    num_steps = int(input("Enter number of steps (e.g., 20): ") or 20)
except ValueError:
    print("Invalid input! Falling back to defaults: 5 agents, 10x10 grid, 20 steps.")
    num_agents, grid_size, num_steps = 5, 10, 20

# -------- Agent Definition -----------
class RandomWalker(ap.Agent):
    def step(self):
        direction = random.choice([(1,0), (-1,0), (0,1), (0,-1)])
        x, y = self.position
        # Keep agents inside grid
        x = max(0, min(self.model.p.grid_size[0]-1, x + direction[0]))
        y = max(0, min(self.model.p.grid_size[1]-1, y + direction[1]))
        self.position = (x, y)

# -------- Model Definition -----------
class RandomWalkModel(ap.Model):
    def setup(self):
        # Create agents
        self.agents = ap.AgentList(self, self.p.agents, RandomWalker)
        # Initialize random positions
        for agent in self.agents:
            agent.position = (random.randint(0, self.p.grid_size[0]-1),
                              random.randint(0, self.p.grid_size[1]-1))
        # Create grid
        self.grid = ap.Grid(self, self.p.grid_size, torus=False)
        self.grid.add_agents(self.agents)

    def step(self):
        for agent in self.agents:
            agent.step()

# -------- Parameters from user input -----------
parameters = {
    'agents': num_agents,
    'grid_size': (grid_size, grid_size),
    'steps': num_steps
}

# -------- Run Model -----------
model = RandomWalkModel(parameters)
model.setup()

# -------- Interactive Animation (Colab/iPad Compatible) -----------
fig, ax = plt.subplots(figsize=(6, 6))
ax.set_xlim(-0.5, model.p.grid_size[0] - 0.5)
ax.set_ylim(-0.5, model.p.grid_size[1] - 0.5)
ax.set_xticks(range(model.p.grid_size[0]))
ax.set_yticks(range(model.p.grid_size[1]))
ax.grid(True)
ax.set_title("Random Walk Simulation")

scat = ax.scatter([], [], s=200, color='crimson')

def update(frame):
    if frame > 0:
        model.step()
    x = [agent.position[0] for agent in model.agents]
    y = [agent.position[1] for agent in model.agents]
    scat.set_offsets(list(zip(x, y)))
    return scat,

plt.close(fig)

# Generate HTML5 video player compatible with iPad Safari/Colab
ani = animation.FuncAnimation(fig, update, frames=model.p.steps, blit=True, repeat=False)
HTML(ani.to_jshtml())