# -*- coding: utf-8 -*-
"""Dancel, TA4, CS0065, AN42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OC1uNyZbr2MMw8SFwY7OAqpW5KnCs_pM
"""

# ==========================================
# PART 1: Knowledge Representation (KR) Setup
# ==========================================
print("=== PART 1: Knowledge Representation Setup ===")
print("Let's set up your initial Knowledge Base (KB).")

# Interactive input for KB facts
try:
    temp_input = int(input("Enter current temperature (e.g., 34): ") or 34)
    humidity_input = int(input("Enter humidity percentage (e.g., 80): ") or 80)
    rain_input = input("Is it raining? (true/false, default: true): ").strip().lower() == 'true'
    motion_input = input("Is motion detected? (true/false, default: true): ").strip().lower() == 'true'
    door_input = input("Is the door open? (true/false, default: false): ").strip().lower() == 'true'
except ValueError:
    print("Invalid input detected. Using default baseline values.")
    temp_input, humidity_input, rain_input, motion_input, door_input = 34, 80, True, True, False

knowledge_base = {
    "temperature": temp_input,
    "humidity": humidity_input,
    "is_raining": rain_input,
    "motion_detected": motion_input,
    "door_open": door_input
}

print("\n[Output] Knowledge Base initialized successfully:")
for category, fact in knowledge_base.items():
    print(f" - {category}: {fact}")
print("-" * 50)


# ==========================================
# PART 2: Implement Rule-Based Reasoning (RBR)
# ==========================================
print("=== PART 2: Rule-Based Reasoning (RBR) ===")

# Task 2A: Create at least 3 IF-THEN rules as Python functions
def rule_hot(facts):
    if facts.get("temperature", 0) > 30:
        return "Turn on the aircon"
    return None

def rule_rain(facts):
    if facts.get("is_raining", False):
        return "Bring umbrella and close windows"
    return None

def rule_security(facts):
    if facts.get("motion_detected", True) and facts.get("door_open", False):
        return "Trigger security alert"
    return None

# List of rules
rules_list = [rule_hot, rule_rain, rule_security]

# Task 2B: Implement an Inference Engine
def inference_engine(kb, rules):
    inferred_actions = []
    for rule in rules:
        action = rule(kb)
        if action:
            inferred_actions.append(action)
    return inferred_actions

# Task 2C: Display Output
print("Rule-Based Reasoning Actions:")
actions = inference_engine(knowledge_base, rules_list)
if actions:
    for action in actions:
        print(f" - {action}")
else:
    print(" - No rules triggered with current facts.")
print("-" * 50)


# ==========================================
# PART 3: Implement Case-Based Reasoning (CBR)
# ==========================================
print("=== PART 3: Case-Based Reasoning (CBR) ===")

# Task 3A: Build a Case Base
case_base = [
    {
        "problem": {"won_t_turn_on": True, "strange_noise": False, "indicator_light_off": True},
        "solution": "Check the main power cable and wall outlet connection."
    },
    {
        "problem": {"won_t_turn_on": False, "strange_noise": True, "indicator_light_off": False},
        "solution": "Inspect internal cooling fan for obstructions or dust buildup."
    },
    {
        "problem": {"won_t_turn_on": True, "strange_noise": True, "indicator_light_off": False},
        "solution": "Reset the device circuit breaker and verify fuse integrity."
    }
]

print("Existing Case Base loaded with 3 past cases.")
print("Define a new problem to test Case-Based Reasoning:")

# Interactive prompt for new problem features
p_power = input("Does the device refuse to turn on? (y/n, default: y): ").strip().lower() != 'n'
p_noise = input("Is the device making a strange noise? (y/n, default: n): ").strip().lower() == 'y'
p_light = input("Is the indicator light off? (y/n, default: y): ").strip().lower() != 'n'

new_problem = {
    "won_t_turn_on": p_power,
    "strange_noise": p_noise,
    "indicator_light_off": p_light
}

print("\nNew Problem Features:", new_problem)

# Similarity matching function
def retrieve_most_similar_case(new_prob, cases):
    best_match = None
    max_similarity = -1
    for case in cases:
        common_features = 0
        total_features = len(new_prob)
        for k, v in new_prob.items():
            if case["problem"].get(k) == v:
                common_features += 1
        similarity = common_features / total_features
        if similarity > max_similarity:
            max_similarity = similarity
            best_match = case
    return best_match, max_similarity

# Task 3C: Reuse Step
best_case, similarity_score = retrieve_most_similar_case(new_problem, case_base)
reused_solution = best_case["solution"]
print(f"\n[Reuse Step] Most similar case retrieved (Match Score: {similarity_score * 100:.0f}%):")
print(f" - Suggested Solution: {reused_solution}")

# Task 3D: Revise Step (Interactive prompt)
print("\n[Revise Step]")
user_adjustment = input("Do you want to modify this solution? (Type your custom adjustment or press Enter to accept): ").strip()
if user_adjustment:
    final_solution = user_adjustment
    print("-> Solution revised manually by user.")
else:
    final_solution = reused_solution
    print("-> Solution kept unchanged.")

# Task 3E: Retain Step
new_case = {
    "problem": new_problem,
    "solution": final_solution
}
case_base.append(new_case)
print(f"\n[Retain Step] New case successfully added to the Case Base.")
print(f"Total cases in Case Base now: {len(case_base)}")
print("=" * 50)